### ISSUE TITLE
Reformulate docstrings for codebase

### ISSUE THREAD

**Issue by AbdElOuadoudK** [AbdElOuadoudK/FL-based_CyberIDS#5]
Several components* in the codebase are either **missing** proper docstrings, 
or their existing docstrings are **incomplete** and lack sufficient detail. 
This reduces the ease of understanding the functionality and purpose 
of various parts of the code, making it more difficult for contributors 
and users to work with.

Make sure to follow the below tasks and subtasks in ascending order.

### Tasks:
- [ ] 1. Review codebase and identify missing/inadequate component* docstrings.
- [ ] 2. Add summary, author information, and doc references.
- [ ] 3. Achieve content-related subtasks _(subtasks 1 and 2)_.
- [ ] 4. Add any important notes on component* behavior or ambiguity.
- [ ] 5. Provide GitHub references from `docs/` directory for more information.
- [ ] 6. Ensure that all docstrings follow the [PEP 257](https://peps.python.org/pep-0257/) conventions.

> _(*) A component may be; a function, method, class, module or package._

### For classes, methods, and functions (subtasks 1):
- [ ] 1. Provide descriptions and signatures** of parameters, attributes, and returns.
- [ ] 2. Provide examples from `tests/` directory.

> _(**) Signature refers to; parameters' names, in/out types, and initial values._

### For modules, and packages (subtasks 2):
- [ ] 1. Identify package dependencies _(precedence, and subsequence)_.
- [ ] 2. Provide code versioning.

### Why this is important:
Good documentation through docstrings enhances the readability 
and maintainability of the code, making it easier for current and 
future contributors to work with the codebase.
