### ISSUE TITLE
chore: Reformatting codebase

### ISSUE THREAD

**Issue by AbdElOuadoudK** [AbdElOuadoudK/FL-based_CyberIDS#6]
The codebase suffers from many **inconsistencies**, including declaring identifiers, 
defining docstrings, and statements indentations. The **absence of standardizing 
code** increases difficulty and ambiguity induced by similarities. This issue reduces 
the ease of understanding the functionality and purpose of various parts of 
the code, making it more difficult for contributors and users to work with.

Make sure to follow the below tasks and in ascending order.

### Tasks:
- [ ] 1. Review codebase and identify misformatted parts.
- [ ] 2. Define the signatures* of methods and functions.
- [ ] 3. Adjust code docstrings.
- [ ] 4. Ensure that all scripts follow the [PEP 8](https://peps.python.org/pep-0008/) conventions.

> _(*) Signature refers to; parameters' names, in/out types, and initial values._

To enforce consistent formatting across the project, 
using automatic formatting tools like _black_, _autopep8_, or _isort_ is suggested

### Why this change?
Proper code formatting ensures readability and maintainability, making 
it easier for contributors to work with the codebase and preventing 
errors caused by inconsistent formatting.
