### ISSUE TITLE
chore: create issue to implement multi-threading logic

### ISSUE THREAD

**Issue by AbdElOuadoudK** [AbdElOuadoudK/FL-based_CyberIDS#9]
This commit creates an issue to address the need for implementing 
multi-threading (or multi-processing) in the codebase. The goal is to 
optimize performance by separating **CPU-bound** tasks from **I/O-bound** 
operations. Ensuring a minimal waste of time during unwanted cycles, 
in an asynchronous way.

Make sure to follow the below tasks in ascending order.

### Tasks:
- [ ] 1. Identify CPU-bound sections that can benefit from parallel execution _(typicaly, main methods)_.
- [ ] 2. Identify I/O-bound operations that can be handled concurrently using multi-threading 
_(usually, class methods as `__save_results()`)_.
- [ ] 3. Implement threading to separate these methods from the rest sections.
- [ ] 4. Ensure that changes do not introduce race conditions or thread safety issues _(e.g. Locks)_.
- [ ] 5. Test the performance impact and adjust the optimal threading configurations. 

### Why this is important:
Implementing multi-threading will help maximize resource utilization 
by allowing the CPU to process tasks while I/O operations are 
performed concurrently. This will lead to improved performance, 
especially in areas where heavy computation and I/O overlap.
